force-app/main/default/objects/Coupon_Item__c/Coupon_Item__c.object-meta.xml
<CustomObject>
    <label>Coupon Item</label>
    <nameField>
        <displayFormat>CLS{0000}</displayFormat>
        <label>Coupon Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coupon_Item__c/fields/Coupon_Image__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Image__c</fullName>
    <label>Coupon Image</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Coupon_Item__c/fields/Coupon_Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Item_Name__c</fullName>
    <label>Coupon Item Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coupon_Item__c/fields/Minimum_Redeem_Balance__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Redeem_Balance__c</fullName>
    <label>Minimum Redeem Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Coupon_Item__c/fields/Offer_Code__c.field-meta.xml
<CustomField>
    <fullName>Offer_Code__c</fullName>
    <label>Offer Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coupon_Item__c/fields/Quota__c.field-meta.xml
<CustomField>
    <fullName>Quota__c</fullName>
    <label>Quota</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Coupon_Item__c/fields/Redeem_Once_Only__c.field-meta.xml
<CustomField>
    <fullName>Redeem_Once_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Redeem Once Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Coupon_Item__c/fields/Redeem_Status__c.field-meta.xml
<CustomField>
    <fullName>Redeem_Status__c</fullName>
    <label>Redeem Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VALID</fullName>
            </value>
            <value>
                <fullName>REDEEMED</fullName>
            </value>
            <value>
                <fullName>EXPIRED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Coupon_Item__c/fields/Update_Coupon_Status_on_Redemption__c.field-meta.xml
<CustomField>
    <fullName>Update_Coupon_Status_on_Redemption__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Update Coupon Status on Redemption</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Coupon_Item__c/fields/Update_Customer_Id_on_Coupon_Creation__c.field-meta.xml
<CustomField>
    <fullName>Update_Customer_Id_on_Coupon_Creation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Update Customer Id on Coupon Creation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Coupon_Item__c/fields/Update_Valid_From_on_Coupon_Creation__c.field-meta.xml
<CustomField>
    <fullName>Update_Valid_From_on_Coupon_Creation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Update Valid From on Coupon Creation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Coupon_Item__c/fields/Valid_From_Offset_in_days__c.field-meta.xml
<CustomField>
    <fullName>Valid_From_Offset_in_days__c</fullName>
    <label>Valid From Offset (in days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Coupon_Item__c/fields/Valid_Length_in_days__c.field-meta.xml
<CustomField>
    <fullName>Valid_Length_in_days__c</fullName>
    <label>Valid Length (in days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Coupon_Item__c/fields/Validate_Customer__c.field-meta.xml
<CustomField>
    <fullName>Validate_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Validate Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Coupon_Item__c/fields/Validate_Date__c.field-meta.xml
<CustomField>
    <fullName>Validate_Date__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Validate Date</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Coupon_Item__c/fields/Validate_Status__c.field-meta.xml
<CustomField>
    <fullName>Validate_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Validate Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Coupon_Item__c/recordTypes/Cash.recordType-meta.xml
<RecordType>
    <fullName>Cash</fullName>
    <active>true</active>
    <description>The coupon is used as a payment tender (Face value is defined in coupon item).</description>
    <label>Cash</label>
</RecordType>

force-app/main/default/classes/CashCouponItemManager.cls
@RestResource(urlMapping='/cpitem/cash/*')
global with sharing class CouponItemManager {
    
    @HttpGet
    global static Coupon_Item__c getCouponItemById() {
        RestRequest request = RestContext.request;
        
        String cpItemId = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);
        
        Coupon_Item__c result = [Select Name, RecordTypeId, Coupon_Item_Name__c, Description__c, Face_Value__c, Minimum_Redeem_Balance__c, Offer_Code__c, Redeem_Status__c, Validate_Status__c From Coupon_Item__c where Name=:cpItemId];
        
        return result;
    }
    
    @HttpPost
    global static Coupon_Item__c createCashCpItem(
        String cp_Coupon_Image, 
        String cp_Coupon_Item_Name, 
        String cp_Description, 
        Decimal cp_Face_Value, 
        Decimal cp_Minimum_Redeem_Balance, 
        String cp_Offer_Code, 
        Integer cp_Quota, 
        Boolean cp_Redeem_Once_Only, 
        String cp_Redeem_Status,
        Boolean cp_Update_Coupon_Status_on_Redemption,
        Boolean cp_Update_Customer_Id_on_Coupon_Creation,
        Boolean cp_Update_Valid_From_on_Coupon_Creation,
        Boolean cp_Validate_Customer,
        Boolean cp_Validate_Date,
        Boolean cp_Validate_Status,
        Integer cp_Valid_From_Offset_in_days,
        Integer cp_Valid_Length_in_days
        ) {
        Coupon_Item__c newcp = new Coupon_Item__c(
            Coupon_Image__c = cp_Coupon_Image,
            Coupon_Item_Name__c = cp_Coupon_Item_Name,
            Description__c = cp_Description,
            Face_Value__c = cp_Face_Value,
            Minimum_Redeem_Balance__c = cp_Minimum_Redeem_Balance,
            Offer_Code__c = cp_Offer_Code,
            Quota__c = cp_Quota,
            Redeem_Once_Only__c = cp_Redeem_Once_Only,
            Redeem_Status__c = cp_Redeem_Status,
            Update_Coupon_Status_on_Redemption__c = cp_Update_Coupon_Status_on_Redemption,
            Update_Customer_Id_on_Coupon_Creation__c = cp_Update_Customer_Id_on_Coupon_Creation,
            Update_Valid_From_on_Coupon_Creation__c = cp_Update_Valid_From_on_Coupon_Creation,
            Validate_Customer__c = cp_Validate_Customer,
            Validate_Date__c = cp_Validate_Date, 
            Validate_Status__c = cp_Validate_Status,
            Valid_From_Offset_in_days__c = cp_Valid_From_Offset_in_days,
            Valid_Length_in_days__c = cp_Valid_Length_in_days
        );
        
        insert newcp;
        return newcp;
    }

    @HttpPut
    global static String updateCashCpItem(String cp_itemid, String cp_status){
        Coupon_Item__c thisCp = [Select Redeem_Status__c From Coupon_Item__c where Name=:cp_itemid];
        thisCp.Redeem_Status__c = cp_status;
        update thisCp;
        return 'Record updated';
    }
}